# Generated by Django 2.2.7 on 2020-04-07 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xforce_transactions', '0001_initial'),
        ('cash_buyer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=255)),
                ('llc_purchase_name', models.CharField(max_length=500)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('Work', 'Work'), ('Home', 'Home'), ('Other', 'Other')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Work', 'Work'), ('Home', 'Home'), ('Main', 'Main'), ('Work Fax', 'Work Fax'), ('Private Fax', 'Private Fax'), ('Other', 'Other')], max_length=20)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('offer_amount', models.IntegerField(default=0)),
                ('offer_accepted', models.BooleanField(default=False)),
                ('additional_details', models.CharField(max_length=500)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('investor_type', models.CharField(choices=[('Rahabber', 'Rahabber'), ('Developer', 'Developer'), ('Builder', 'Builder'), ('Buy/Hold', 'Buy/Hold'), ('Realtor', 'Realtor'), ('Wholesaler', 'Wholesaler'), ('Private Buyer', 'Private Buyer')], max_length=10)),
                ('targeted_area', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=20)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('counter_email_offer_sent', models.BooleanField(default=False)),
                ('pending_email_sent', models.BooleanField(default=False)),
                ('sold_email_sent', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='sales_offer/')),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('earnest_money_deposit', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deals', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('No Value', 'No Value'), ('Pending', 'Pending'), ('Markeing', 'Markeing'), ('Schedule and Showing', 'Schedule and Showing'), ('Follow up/offer', 'Follow up/offer'), ('Offer accepted', 'Offer accepted'), ('Assigned', 'Assigned'), ('$$$CLOSED$$$', '$$$CLOSED$$$'), ('Dead', 'Dead'), ('Renegotiate!', 'Renegotiate!')], default='no value', max_length=255)),
                ('deadline_to_assign', models.DateTimeField(blank=True, null=True)),
                ('email_blast', models.BooleanField(default=False)),
                ('facebook_groups', models.BooleanField(default=False)),
                ('call_vips', models.BooleanField(default=False)),
                ('mls_cash_buyer', models.BooleanField(default=False)),
                ('text_vip_buyers', models.BooleanField(default=False)),
                ('marketing_price', models.IntegerField(blank=True, null=True)),
                ('buy_now_price', models.IntegerField(default=False)),
                ('mls_price', models.CharField(blank=True, max_length=255, null=True)),
                ('comps', models.CharField(blank=True, max_length=500, null=True)),
                ('arv', models.IntegerField(blank=True, null=True)),
                ('lockbox_acess_info', models.CharField(blank=True, max_length=500, null=True)),
                ('website_pictures', models.URLField()),
                ('showing_date', models.DateTimeField(blank=True, null=True)),
                ('set_showing', models.CharField(choices=[('no value', 'no value'), ('Offer Accepted(Back to Tranastion)', 'Offer Accepted(Back to Tranastion)')], max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('submitted_offers', models.CharField(max_length=500)),
                ('showing', models.CharField(choices=[('Showing Complete', 'Showing Complete'), ('No Showing Needed', 'No Showing Needed')], max_length=255)),
                ('final_gross_sales_price', models.IntegerField(blank=True, null=True)),
                ('buyer_entity_name', models.CharField(max_length=500)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('finders_fee', models.IntegerField(blank=True, null=True)),
                ('assigned', models.BooleanField(default=False)),
                ('email_subject', models.CharField(max_length=500)),
                ('email_content', models.CharField(blank=True, max_length=500, null=True)),
                ('send_email', models.CharField(choices=[('no value', 'no value'), ('Send Email Content Above', 'Send Email Content Above'), ('Best and Highest', 'Best and Highest'), ('Pending Property', 'Pending Property'), ('Sold Property', 'Sold Property')], default='no value', max_length=255)),
                ('marketing_done', models.BooleanField(default=False)),
                ('files', models.FileField(blank=True, default=None, null=True, upload_to='sales/')),
                ('accepted_buyers', models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_buyer', to='cash_buyer.Cash_Buyer')),
                ('attending_showing', models.ForeignKey(max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attending_showing', to='cash_buyer.Cash_Buyer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('current_interest', models.ForeignKey(max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_interest', to='cash_buyer.Cash_Buyer')),
                ('disposition_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposition_manager', to=settings.AUTH_USER_MODEL)),
                ('transactions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='xforce_transactions.Transaction')),
            ],
        ),
    ]
