# Generated by Django 2.2.7 on 2020-04-10 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='accepted_buyers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_buyer', to='cash_buyer.Cash_Buyer'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='attending_showing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attending_showing', to='cash_buyer.Cash_Buyer'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='buy_now_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='buyer_entity_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='current_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_interest', to='cash_buyer.Cash_Buyer'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='deals',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='disposition_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disposition_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sales',
            name='email_subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='submitted_offers',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='website_pictures',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='earnest_money_deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='offer_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='property',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
