# Generated by Django 2.2.7 on 2020-04-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_sales', '0002_auto_20200410_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='submitted_offers',
        ),
        migrations.AlterField(
            model_name='sales',
            name='deals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='xforce_transactions.Transaction'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='set_showing',
            field=models.CharField(choices=[('no value', 'no value'), ('Offer Accepted(Back to Transaction)', 'Offer Accepted(Back to Transaction)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='xforce_sales.sales'),
        ),
    ]
