# Generated by Django 2.2.7 on 2020-04-15 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_sales', '0003_auto_20200413_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_offer',
            name='via_webform',
            field=models.CharField(default='no', max_length=6),
        ),
        migrations.AlterField(
            model_name='sales',
            name='send_email',
            field=models.CharField(blank=True, choices=[('no value', 'no value'), ('Send Email Content Above', 'Send Email Content Above'), ('Best and Highest', 'Best and Highest'), ('Pending Property', 'Pending Property'), ('Sold Property', 'Sold Property')], default='no value', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='set_showing',
            field=models.CharField(blank=True, choices=[('no value', 'no value'), ('Offer Accepted(Back to Transaction)', 'Offer Accepted(Back to Transaction)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='showing',
            field=models.CharField(blank=True, choices=[('Showing Complete', 'Showing Complete'), ('No Showing Needed', 'No Showing Needed')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Pending', 'Pending'), ('Markeing', 'Markeing'), ('Schedule and Showing', 'Schedule and Showing'), ('Follow up/offer', 'Follow up/offer'), ('Offer accepted', 'Offer accepted'), ('Assigned', 'Assigned'), ('$$$CLOSED$$$', '$$$CLOSED$$$'), ('Dead', 'Dead'), ('Renegotiate!', 'Renegotiate!')], default='no value', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='additional_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='investor_type',
            field=models.CharField(blank=True, choices=[('Rahabber', 'Rahabber'), ('Developer', 'Developer'), ('Builder', 'Builder'), ('Buy/Hold', 'Buy/Hold'), ('Realtor', 'Realtor'), ('Wholesaler', 'Wholesaler'), ('Private Buyer', 'Private Buyer')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('Mobile', 'Mobile'), ('Work', 'Work'), ('Home', 'Home'), ('Main', 'Main'), ('Work Fax', 'Work Fax'), ('Private Fax', 'Private Fax'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='targeted_area',
            field=models.CharField(blank=True, choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
