# Generated by Django 2.2.7 on 2020-04-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_sales', '0004_auto_20200415_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_offer',
            name='to_date',
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='email_type',
            field=models.CharField(blank=True, choices=[('Work', 'Work'), ('Home', 'Home'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='full_name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='llc_purchase_name',
            field=models.CharField(max_length=75),
        ),
    ]
