# Generated by Django 2.2.7 on 2020-04-17 07:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_sales', '0005_auto_20200416_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_offer',
            name='close_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='earnest_money_deposit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='offer_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='xforce_sales.sales'),
        ),
        migrations.AlterField(
            model_name='sales_offer',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
