# Generated by Django 2.2.7 on 2020-04-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_sales', '0006_auto_20200417_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_offer',
            name='add_cash_buyer',
            field=models.BooleanField(default=False),
        ),
    ]
