# Generated by Django 2.2.7 on 2020-04-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_sales', '0007_sales_offer_add_cash_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='status',
            field=models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Pending', 'Pending'), ('Marketing', 'Marketing'), ('Follow up / Offer', 'Follow up / Offer'), ('Schedule and Showing', 'Schedule and Showing'), ('Offer Accepted', 'Offer Accepted'), ('Assigned', 'Assigned'), ('$$$Closed$$$', '$$$Closed$$$'), ('Dead', 'Dead'), ('Renegotiate!', 'Renegotiate!')], default='no value', max_length=255, null=True),
        ),
    ]
