# Generated by Django 2.2.7 on 2020-04-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_sales', '0008_auto_20200421_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='assigned',
            field=models.CharField(blank=True, choices=[('no value', 'no value'), ('Offer Accepted(Back to Transaction)', 'Offer Accepted(Back to Transaction)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='set_showing',
            field=models.BooleanField(default=False),
        ),
    ]
