# Generated by Django 2.2.7 on 2020-04-28 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_sales', '0009_auto_20200422_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_offer',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
