# Generated by Django 2.2.7 on 2020-04-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_sales', '0011_auto_20200429_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='from_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
