# Generated by Django 2.2.7 on 2020-04-07 13:22

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_id', models.CharField(max_length=20)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InviteUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=10)),
                ('sub_id', models.CharField(default=django.contrib.auth.models.User, max_length=10)),
                ('click', models.IntegerField(default=0)),
                ('sign_up', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvitePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.IntegerField(default=0)),
                ('new_user', models.IntegerField(default=0)),
                ('inv_user', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('invite_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.InviteUrl')),
            ],
        ),
    ]
