# Generated by Django 2.2.7 on 2020-04-07 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_name', models.CharField(choices=[('cold', 'cold'), ('warm', 'warm'), ('hot', 'hot')], default='warm', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Temperature',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_name', models.CharField(choices=[('minutes', 'minutes'), ('hours', 'hours'), ('days', 'days')], default='minutes', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Time',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('email', 'email')], default='email', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Type',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_all_day_task', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('link', models.CharField(default='http://127.0.0.1:8000/', max_length=200)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.Temperature')),
            ],
            options={
                'verbose_name_plural': 'Task',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_count', models.IntegerField()),
                ('sent', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.Task')),
                ('time_type', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='task_management.Time')),
                ('type_email', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='task_management.Type')),
            ],
            options={
                'verbose_name_plural': 'Reminder',
            },
        ),
    ]
