# Generated by Django 2.2.7 on 2020-04-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_prospects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='skip_traced',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='prospect_properties',
            name='skip_traced',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
