# Generated by Django 2.2.7 on 2020-06-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_prospects', '0002_auto_20200410_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
