# Generated by Django 2.2.7 on 2020-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_pill',
            name='sms_notification',
            field=models.BooleanField(default=False),
        ),
    ]
