# Generated by Django 2.2.7 on 2020-04-07 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XforceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('entity_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('disposition_company_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email_subject_for_comment', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sms_phone_number', models.CharField(blank=True, default=None, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_number', models.CharField(blank=True, default=None, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('website', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('logo', models.FileField(blank=True, default=None, null=True, upload_to='settings_logo/')),
                ('seller_missed_call_text', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('missed_call_trigger', models.BooleanField(blank=True, default=False, null=True)),
                ('best_and_highest_email_template', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pending_property_email_template', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sold_property_email_template', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('setting_file', models.FileField(blank=True, default=None, null=True, upload_to='xforce_settings_files/')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Title_Company_Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email_body', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('setting', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_company', to='xforce_settings.XforceSettings')),
            ],
        ),
        migrations.CreateModel(
            name='E_Signature_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('message', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('requester_name', models.EmailField(blank=True, default=None, max_length=50, null=True)),
                ('requester_email', models.EmailField(blank=True, default=None, max_length=50, null=True)),
                ('reminders', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('setting', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_signature', to='xforce_settings.XforceSettings')),
            ],
        ),
        migrations.CreateModel(
            name='ContractTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('Assignment', 'Assignment')], default=None, max_length=25, null=True)),
                ('contract_email_subject', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('contract_email_body', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('contract_text', models.TextField(blank=True, default=None, max_length=3000, null=True)),
                ('setting', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='xforce_settings.XforceSettings')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('escrow_officer', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('company_img', models.FileField(blank=True, default=None, null=True, upload_to='company/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Callrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('account_number', models.IntegerField()),
                ('company_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('setting', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callrail', to='xforce_settings.XforceSettings')),
            ],
        ),
        migrations.CreateModel(
            name='CallAndOfferAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callandofferattempts_type', models.CharField(blank=True, choices=[('1st Call Attempt SMS', '1st Call Attempt SMS'), ('2nd Call Attempt SMS', '2nd Call Attempt SMS'), ('3rd call Attempt SMS', '3rd call Attempt SMS'), ('4th call Attempt SMS', '4th call Attempt SMS'), ('Final call Attempt SMS', 'Final call Attempt SMS'), ('After Speaking with Seller SMS', 'After Speaking with Seller SMS'), ('1st Call Attempt Email', '1st Call Attempt Email'), ('2nd Call Attempt Email', '2nd Call Attempt Email'), ('3rd Call Attempt Email', '3rd Call Attempt Email'), ('4th Call Attempt Email', '4th Call Attempt Email'), ('Final Call Attempt Email', 'Final Call Attempt Email'), ('After Speaking with Seller Email', 'After Speaking with Seller Email'), ('1st Offer Attempt SMS', '1st Offer Attempt SMS'), ('2nd Offer Attempt SMS', '2nd Offer Attempt SMS'), ('3rd Offer Attempt SMS', '3rd Offer Attempt SMS'), ('4th Offer Attempt SMS', '4th Offer Attempt SMS'), ('Final Offer Made SMS', 'Final Offer Made SMS'), ('1st Offer Attempt Email', '1st Offer Attempt Email'), ('2nd Offer Attempt Email', '2nd Offer Attempt Email'), ('3rd Offer Attempt Email', '3rd Offer Attempt Email'), ('4th Offer Attempt Email', '4th Offer Attempt Email'), ('Final Offer Made Email', 'Final Offer Made Email')], default=None, max_length=25, null=True)),
                ('callandofferattempts_sms', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('callandofferattempts_subject', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('callandofferattempts_body', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('callandofferattempts_action', models.CharField(blank=True, choices=[('SMS Only', 'SMS Only'), ('Email Only', 'Email Only'), ('Send Both', 'Send Both')], default=None, max_length=50, null=True)),
                ('setting', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_and_offers', to='xforce_settings.XforceSettings')),
            ],
        ),
    ]
