# Generated by Django 2.2.7 on 2020-04-07 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkipTraceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256, null=True)),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('total_records', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('existing_matches', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('existing_match_savings', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('total_hits', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('hits_percentage', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('total_cost', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('sheet_name', models.CharField(blank=True, max_length=256, null=True)),
                ('destination_fields', models.CharField(max_length=1000, null=True)),
                ('is_process_complete', models.BooleanField(default=False)),
                ('existing_file', models.BooleanField(default=False)),
                ('records_created', models.BooleanField(default=False)),
                ('should_trace', models.BooleanField(default=False)),
                ('fail_reason', models.CharField(default='-', max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SkipTraceFile',
            },
        ),
        migrations.CreateModel(
            name='SingleSkipTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('full_name', models.CharField(blank=True, default=' ', max_length=1000, null=True)),
                ('file_name', models.CharField(blank=True, default='#', max_length=1000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('property_address', models.CharField(max_length=256, null=True)),
                ('property_address2', models.CharField(blank=True, max_length=256, null=True)),
                ('property_city', models.CharField(max_length=256, null=True)),
                ('property_state', models.CharField(max_length=256, null=True)),
                ('property_zip', models.CharField(max_length=256, null=True)),
                ('mailing_address', models.CharField(blank=True, max_length=256, null=True)),
                ('mailing_address2', models.CharField(blank=True, max_length=256, null=True)),
                ('mailing_city', models.CharField(blank=True, max_length=256, null=True)),
                ('mailing_state', models.CharField(blank=True, max_length=256, null=True)),
                ('mailing_zip', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, default=' ', max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, default=' ', max_length=1000, null=True)),
                ('address', models.CharField(blank=True, default=' ', max_length=1000, null=True)),
                ('api_response', models.TextField(blank=True, null=True)),
                ('is_validation_complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrepaidBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skiptrace_price', models.DecimalField(decimal_places=2, default=0.85, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PrepaidBalance',
            },
        ),
        migrations.CreateModel(
            name='PhoneTraced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('skiptrace', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='skiptrace.SingleSkipTrace')),
            ],
            options={
                'verbose_name_plural': 'PhoneTraced',
            },
        ),
        migrations.CreateModel(
            name='EmailTraced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('skiptrace', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='skiptrace.SingleSkipTrace')),
            ],
            options={
                'verbose_name_plural': 'EmailTraced',
            },
        ),
        migrations.CreateModel(
            name='DestinationFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('full_name', models.CharField(blank=True, default=' ', max_length=1000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('property_address', models.CharField(max_length=256, null=True)),
                ('property_address2', models.CharField(blank=True, max_length=256, null=True)),
                ('property_city', models.CharField(max_length=256, null=True)),
                ('property_state', models.CharField(max_length=256, null=True)),
                ('property_zip', models.CharField(max_length=256, null=True)),
                ('mailing_address', models.CharField(blank=True, max_length=256, null=True)),
                ('mailing_address2', models.CharField(blank=True, max_length=256, null=True)),
                ('mailing_city', models.CharField(blank=True, max_length=256, null=True)),
                ('mailing_state', models.CharField(blank=True, max_length=256, null=True)),
                ('mailing_zip', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, default=' ', max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, default=' ', max_length=1000, null=True)),
                ('address', models.CharField(blank=True, default=' ', max_length=1000, null=True)),
                ('api_response', models.TextField(blank=True, null=True)),
                ('is_validation_complete', models.BooleanField(default=False)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skiptrace.SkipTraceFile')),
            ],
        ),
        migrations.CreateModel(
            name='AddressTraced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('skiptrace', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='skiptrace.SingleSkipTrace')),
            ],
            options={
                'verbose_name_plural': 'AddressTraced',
            },
        ),
    ]
