# Generated by Django 2.2.7 on 2020-04-07 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filter_prospects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('market', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'MajorMarket',
            },
        ),
        migrations.CreateModel(
            name='MarketingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Cold Call', 'Cold Call'), ('Direct Mail', 'Direct Mail'), ('Voice Broadcast', 'Voice Broadcast'), ('RVM', 'RVM'), ('SMS', 'SMS'), ('EMAIL', 'EMAIL')], default='Cold Call', max_length=255)),
                ('touch_rounds', models.IntegerField(default=0)),
                ('break_into', models.IntegerField(default=0)),
                ('current_round', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('days_gap_in_campaign', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('send_on', models.CharField(blank=True, default='M-S', max_length=20, null=True)),
                ('scheduled_plan_for', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'MarketingPlan',
            },
        ),
        migrations.CreateModel(
            name='PlanRoundTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('detail', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('more_info', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('touch_round_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('touch_status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('InActive', 'InActive')], default='Active', max_length=255)),
                ('touch_round_after_days', models.IntegerField(default=0)),
                ('touch_file', models.FileField(blank=True, null=True, upload_to='touch_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='marketing_machine.MarketingPlan')),
            ],
            options={
                'verbose_name_plural': 'PlanRoundTemplate',
            },
        ),
        migrations.CreateModel(
            name='MarketingSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('InActive', 'InActive')], default='Pending', max_length=255)),
                ('temperature', models.CharField(choices=[('Cold', 'Cold'), ('Warm', 'Warm'), ('Hot', 'Hot')], default='Cold', max_length=255)),
                ('details', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('planning_status', models.CharField(choices=[('Untouched', 'Untouched'), ('Filtered', 'Filtered'), ('Skipped', 'Skipped'), ('Planned', 'Planned')], default='Untouched', max_length=255)),
                ('create_marketing', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255)),
                ('planning_done', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255)),
                ('is_completed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255)),
                ('timezone_gap_in_hours', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='filter_prospects.List')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MarketingSequence',
            },
        ),
        migrations.AddField(
            model_name='marketingplan',
            name='sequence',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_machine.MarketingSequence'),
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('campaigning_status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent')], default='Pending', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hash_off', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('temperature', models.CharField(choices=[('Cold', 'Cold'), ('Warm', 'Warm'), ('Hot', 'Hot')], default='Cold', max_length=255)),
                ('distribution_status', models.CharField(choices=[('Pending', 'Pending'), ('Untouched', 'Untouched'), ('Completed', 'Completed')], default='Pending', max_length=255)),
                ('approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved to Merchant', 'Approved to Merchant')], default='Pending', max_length=255)),
                ('total_units', models.IntegerField(default=0)),
                ('scheduled_plan_for', models.DateTimeField(blank=True, null=True)),
                ('timezone_gap_in_hours', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('days_gap_in_campaign', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('notes', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('marketing_details', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('break_into', models.IntegerField(default=0)),
                ('send_on', models.CharField(blank=True, default='M-S', max_length=20, null=True)),
                ('time_format', models.CharField(blank=True, default='AM', max_length=20, null=True)),
                ('campaign_file', models.FileField(blank=True, null=True, upload_to='campaign_files/')),
                ('campaign_records_list', models.TextField(blank=True, default='', null=True)),
                ('current_campaign', models.BooleanField(default=False)),
                ('is_single', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camp_sequence', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_machine.MarketingSequence')),
                ('maj_market', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_machine.MajorMarket')),
                ('plan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing_machine.MarketingPlan')),
                ('responsible', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible', to=settings.AUTH_USER_MODEL)),
                ('template', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing_machine.PlanRoundTemplate')),
            ],
            options={
                'verbose_name_plural': 'MarketingCampaign',
            },
        ),
        migrations.CreateModel(
            name='CampaignManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Cold Call', 'Cold Call'), ('Direct Mail', 'Direct Mail'), ('Voice Broadcast', 'Voice Broadcast'), ('RVM', 'RVM'), ('SMS', 'SMS'), ('EMAIL', 'EMAIL')], default='Cold Call', max_length=255)),
                ('current_round', models.IntegerField(default=0)),
                ('prospect', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='filter_prospects.Prospect_Properties')),
                ('sequence', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='marketing_machine.MarketingSequence')),
            ],
            options={
                'verbose_name_plural': 'CampaignManagement',
            },
        ),
    ]
