# Generated by Django 2.2.7 on 2020-04-07 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xforce_seller_leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xforce_settings', '0001_initial'),
        ('cash_buyer', '0001_initial'),
        ('marketing_machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Pending', 'Pending'), ('Marketing', 'Marketing'), ('Follow up / Offer', 'Follow up / Offer'), ('Schedule and Showing', 'Schedule and Showing'), ('Offer Accepted', 'Offer Accepted'), ('Assigned', 'Assigned'), ('$$$Closed$$$', '$$$Closed$$$'), ('Dead', 'Dead'), ('Renegotiate!', 'Renegotiate!')], max_length=50, null=True)),
                ('potential', models.CharField(choices=[('No Value', 'No Value'), ('Wholesale', 'Wholesale'), ('Asset', 'Asset'), ('Fix and Flip', 'Fix and Flip')], max_length=50)),
                ('wait_for_refund', models.BooleanField(default=False)),
                ('pending_stage', models.CharField(blank=True, choices=[('No Value', 'No Value'), ('1-Receive Contract', '1-Receive Contract'), ('2-Contract Send To Title Company', '2-Contract Send To Title Company'), ('3-EMD Wired', '3-EMD Wired')], max_length=50, null=True)),
                ('hoa', models.BooleanField(default=False)),
                ('preliminary_received', models.BooleanField(default=False)),
                ('reason_for_pending', models.TextField(blank=True, max_length=500, null=True)),
                ('purchase_contract_ratification_date_start', models.DateTimeField(null=True)),
                ('purchase_contract_ratification_date_end', models.DateTimeField(null=True)),
                ('contract_date_start', models.DateTimeField(blank=True, null=True)),
                ('contract_date_end', models.DateTimeField(blank=True, null=True)),
                ('contract_price', models.IntegerField(blank=True, null=True)),
                ('original_purchase_emd_amount', models.IntegerField(blank=True, null=True)),
                ('wire_confirmation_number', models.TextField(blank=True, max_length=500, null=True)),
                ('title_actions', models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Email Contract To Title', 'Email Contract To Title'), ('Email Wire Number To Title', 'Email Wire Number To Title')], max_length=50, null=True)),
                ('marketing_Stage', models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Not Started', 'Not Started'), ('Pending', 'Pending'), ('Offer Accepted', 'Offer Accepted'), ('Done! Buyer Found', 'Done! Buyer Found'), ('Not Applicable', 'Not Applicable')], max_length=50, null=True)),
                ('marketing_needs', models.BooleanField(default=False)),
                ('marketing_price', models.IntegerField(blank=True, null=True)),
                ('website_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('showing_date_start', models.DateTimeField(blank=True, null=True)),
                ('showing_date_end', models.DateTimeField(blank=True, null=True)),
                ('deadline_to_accept_offer_start', models.DateTimeField(blank=True, null=True)),
                ('deadline_to_accept_offer_end', models.DateTimeField(blank=True, null=True)),
                ('showing', models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Showing Complete', 'Showing Complete'), ('Not Showing Needed', 'Not Showing Needed')], max_length=50, null=True)),
                ('pre_assigned_status', models.BooleanField(default=False)),
                ('assignment_stage', models.CharField(blank=True, choices=[('No Value', 'No Value'), ('1- Assignment Send', '1- Assignment Send'), ('2- Assignment Received', '2- Assignment Received'), ('3- Assignment Send To Title Company', '3- Assignment Send To Title Company'), ('4- EMD Deposit', '4- EMD Deposit'), ('5- Set Closing Time', '5- Set Closing Time')], max_length=50, null=True)),
                ('final_gross_sales_price', models.IntegerField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('finder_fee', models.IntegerField(blank=True, null=True)),
                ('buyer_entity_name', models.CharField(blank=True, max_length=25, null=True)),
                ('assignment_emd_amount', models.IntegerField(blank=True, null=True)),
                ('non_refundable', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('emd_date_start', models.DateTimeField(blank=True, null=True)),
                ('emd_date_end', models.DateTimeField(blank=True, null=True)),
                ('assignment_fee', models.IntegerField(blank=True, null=True)),
                ('other_terms', models.TextField(blank=True, max_length=500, null=True)),
                ('contract_action', models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Generate Assignment Contract', 'Generate Assignment Contract'), ('Email Assignment Contract', 'Email Assignment Contract'), ('Email Assignment Contract To Title', 'Email Assignment Contract To Title')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('misc_expenses', models.IntegerField(blank=True, null=True)),
                ('explanation_of_misc_expense', models.TextField(blank=True, max_length=500, null=True)),
                ('actual_profit', models.IntegerField(blank=True, null=True)),
                ('closing_stage', models.BooleanField(default=False)),
                ('lead_source', models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Telemarketing', 'Telemarketing'), ('Direct Mail', 'Direct Mail'), ('PPC', 'PPC'), ('Social', 'Social'), ('Organic', 'Organic'), ('Generic', 'Generic'), ('Referral', 'Referral'), ('Voice Broadcast', 'Voice Broadcast'), ('RVM', 'RVM'), ('SMS', 'SMS'), ('JV', 'JV'), ('Bandit Signs', 'Bandit Signs')], max_length=50, null=True)),
                ('contract_delivery', models.CharField(blank=True, choices=[('No Value', 'No Value'), ('eSignature', 'eSignature'), ('Email', 'Email'), ('In Person', 'In Person')], max_length=50, null=True)),
                ('detailed_source', models.TextField(blank=True, max_length=500, null=True)),
                ('acq_sys_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('dispo_sys_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_file', models.FileField(blank=True, null=True, upload_to='Transactions_Files/')),
                ('buyer_contact_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_buyer', to='cash_buyer.Cash_Buyer')),
                ('campaigns', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_for_transaction', to='marketing_machine.MarketingCampaign')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_for_transaction', to='xforce_settings.Company')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='xforce_seller_leads.SellerLead')),
                ('transaction_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_for_transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
