# Generated by Django 2.2.7 on 2020-04-13 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_transactions', '0002_auto_20200410_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='campaigns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_for_transaction', to='marketing_machine.MarketingCampaign'),
        ),
    ]
