# Generated by Django 2.2.7 on 2020-04-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_transactions', '0003_auto_20200413_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='deadline_to_accept_offer_end',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='emd_date_end',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='showing_date_end',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='marketing_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
