# Generated by Django 2.2.7 on 2020-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_transactions', '0005_auto_20200416_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='final_gross_sales_price',
            field=models.IntegerField(default=0),
        ),
    ]
