# Generated by Django 2.2.7 on 2020-04-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_transactions', '0006_auto_20200422_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='explanation_of_misc_expense',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='other_terms',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reason_for_pending',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
