# Generated by Django 2.2.7 on 2020-05-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_transactions', '0008_transaction_from_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Pending', 'Pending'), ('Marketing', 'Marketing'), ('Follow up / Offer', 'Follow up / Offer'), ('Schedule and Showing', 'Schedule and Showing'), ('Offer Accepted', 'Offer Accepted'), ('Assigned', 'Assigned'), ('Closed', 'Closed'), ('Dead', 'Dead'), ('Renegotiate!', 'Renegotiate!')], max_length=50, null=True),
        ),
    ]
