# Generated by Django 2.2.7 on 2020-04-07 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xforce_settings', '0001_initial'),
        ('marketing_machine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SellerLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(blank=True, max_length=150, null=True)),
                ('tracker', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('seller_email', models.EmailField(blank=True, max_length=75, null=True)),
                ('property_address_map', models.TextField(blank=True, max_length=200, null=True)),
                ('total_view', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('outbound_call_lead', models.BooleanField(default=False)),
                ('stage_of_contact', models.CharField(choices=[('No Value', 'No Value'), ('No Attempt', 'No Attempt'), ('Call Attempt 1', 'Call Attempt 1'), ('Call Attempt 2', 'Call Attempt 2'), ('Call Attempt 3', 'Call Attempt 3'), ('Call Attempt 4', 'Call Attempt 4'), ('Final Attempt > 1', 'Final Attempt > 1'), ('CONTACTED', 'CONTACTED')], max_length=50, null=True)),
                ('lead_status', models.CharField(choices=[('No Value', 'No Value'), ('New Untouched', 'New Untouched'), ('Discovery', 'Discovery'), ('**Interested--> Updated Offer Status', '**Interested--> Updated Offer Status'), ('Not Interested / Follow Up', 'Not Interested / Follow Up'), ('DO NOT CONTACT', 'DO NOT CONTACT'), ('Solicitation Call / Wrong # / Other', 'Solicitation Call / Wrong # / Other'), ('Wants Retails', 'Wants Retails')], max_length=50, null=True)),
                ('temperature', models.CharField(choices=[('No Value', 'No Value'), ('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Dead', 'Dead')], max_length=50, null=True)),
                ('follow_up_in', models.CharField(choices=[('No Value', 'No Value'), ('1 Day', '1 Day'), ('2 Days', '2 Days'), ('1 Week', '1 Week'), ('2 Weeks', '2 Weeks'), ('3 Weeks', '3 Weeks'), ('1 Month', '1 Month'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('1 Year', '1 Year')], max_length=50, null=True)),
                ('follow_up_specific_date', models.DateTimeField(null=True)),
                ('set_specific_follow_up', models.BooleanField(default=False)),
                ('need_skip', models.BooleanField(default=False)),
                ('info', models.TextField(blank=True, max_length=500, null=True)),
                ('nurture_campaign_action', models.BooleanField(default=False)),
                ('occupancy', models.CharField(choices=[('No Value', 'No Value'), ('Vacant', 'Vacant'), ('Owner Occupied', 'Owner Occupied'), ('Tenants', 'Tenants')], max_length=20, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('mortgage_amount', models.IntegerField(blank=True, null=True)),
                ('asking_price', models.IntegerField(blank=True, null=True)),
                ('hoa', models.BooleanField(default=False)),
                ('best_call_back_time', models.CharField(blank=True, max_length=150, null=True)),
                ('miscellaneous_notes', models.TextField(blank=True, max_length=500, null=True)),
                ('get_data_from_total_view', models.BooleanField(default=False)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.IntegerField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('tax_assessment', models.IntegerField(blank=True, null=True)),
                ('year_assessed', models.IntegerField(blank=True, null=True)),
                ('property_value', models.IntegerField(blank=True, null=True)),
                ('potential_offer', models.IntegerField(blank=True, null=True)),
                ('arv', models.CharField(blank=True, max_length=100, null=True)),
                ('mao', models.CharField(blank=True, max_length=100, null=True)),
                ('mao_details', models.TextField(blank=True, max_length=500, null=True)),
                ('offer_range', models.CharField(blank=True, max_length=50, null=True)),
                ('made_offer', models.CharField(choices=[('No Value', 'No Value'), ('Make Offer', 'Make Offer'), ('Make Attempt 1', 'Make Attempt 1'), ('Make Attempt 2', 'Make Attempt 2'), ('Make Attempt 3', 'Make Attempt 3'), ('Make Attempt 4 > 1', 'Make Attempt 4 > 1'), ('Made Offer', 'Made Offer'), ('Offer Not Made', 'Offer Not Made')], max_length=20, null=True)),
                ('offer_status', models.CharField(choices=[('No Value', 'No Value'), ('Not Given', 'Not Given'), ('Accepted', 'Accepted'), ('Not Accepted', 'Not Accepted'), ('Negotiating', 'Negotiating')], max_length=255, null=True)),
                ('app_start', models.DateTimeField(blank=True, null=True)),
                ('app_end', models.DateTimeField(blank=True, null=True)),
                ('set_appointment', models.BooleanField(blank=True, null=True)),
                ('note_for_agent', models.TextField(blank=True, max_length=500, null=True)),
                ('canceled_appointment', models.BooleanField(blank=True, default=False, null=True)),
                ('contract_offer_amt', models.IntegerField(blank=True, null=True)),
                ('emd', models.CharField(blank=True, max_length=100, null=True)),
                ('closing_costs', models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Each Party to Pay his or her Own Costs', 'Each Party to Pay his or her Own Costs'), ('Paid in Full By Buyer', 'Paid in Full By Buyer')], max_length=50, null=True)),
                ('closing_no_day', models.IntegerField(blank=True, null=True)),
                ('to_vacate_on', models.CharField(blank=True, max_length=100, null=True)),
                ('other_terms', models.TextField(blank=True, max_length=500, null=True)),
                ('deal_details', models.TextField(blank=True, max_length=500, null=True)),
                ('deal_action', models.BooleanField(blank=True, default=False, null=True)),
                ('contract_delivery', models.CharField(choices=[('No Value', 'No Value'), ('E Signature', 'E Signature'), ('Email', 'Email'), ('In Person', 'In Person')], max_length=20, null=True)),
                ('contract_action', models.CharField(choices=[('No Value', 'No Value'), ('Generate Contract', 'Generate Contract'), ('Email Contract', 'Email Contract')], max_length=20, null=True)),
                ('call_log', models.CharField(blank=True, max_length=500, null=True)),
                ('sms_log', models.CharField(blank=True, max_length=500, null=True)),
                ('lead_source', models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Telemarketing', 'Telemarketing'), ('Direct Mail', 'Direct Mail'), ('PPC', 'PPC'), ('Social', 'Social'), ('Organic', 'Organic'), ('Generic', 'Generic'), ('Referral', 'Referral'), ('Voice Broadcast', 'Voice Broadcast'), ('SMS', 'SMS'), ('RVM', 'RVM'), ('JV', 'JV'), ('Bandit Signs', 'Bandit Signs'), ('Expired Listing', 'Expired Listing')], max_length=20, null=True)),
                ('detailed_source', models.TextField(blank=True, max_length=500, null=True)),
                ('deal_status', models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Pending', 'Pending'), ('Marketing', 'Marketing'), ('Assigned', 'Assigned'), ('$$$Closed$$$', '$$$Closed$$$'), ('Dead', 'Dead')], max_length=20, null=True)),
                ('actions', models.CharField(choices=[('No Value', 'No Value'), ('Send To E-Sign', 'Send To E-Sign'), ('Send To E-Sign Base 64', 'Send To E-Sign Base 64')], max_length=255, null=True)),
                ('lead_file', models.FileField(null=True, upload_to='seller_lead_files/')),
                ('campaign', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_for_seller_lead', to='marketing_machine.MarketingCampaign')),
                ('lead_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_by', to=settings.AUTH_USER_MODEL)),
                ('lead_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('major_market', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='major_market', to='marketing_machine.MajorMarket')),
                ('nurture_campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='xforce_seller_leads.FollowUp')),
                ('title_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_for_seller', to='xforce_settings.Company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
