# Generated by Django 2.2.7 on 2020-04-13 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_seller_leads', '0002_auto_20200410_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerlead',
            old_name='app_end',
            new_name='app_date',
        ),
        migrations.RemoveField(
            model_name='sellerlead',
            name='app_start',
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_for_seller_lead', to='marketing_machine.MarketingCampaign'),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='contract_offer_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='emd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='major_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_market', to='marketing_machine.MajorMarket'),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=75, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
