# Generated by Django 2.2.7 on 2020-04-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_seller_leads', '0003_auto_20200413_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerlead',
            name='contract_action',
            field=models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Generate Contract', 'Generate Contract'), ('Email Contract', 'Email Contract'), ('E Signature', 'E Signature')], max_length=20, null=True),
        ),
    ]
