# Generated by Django 2.2.7 on 2020-04-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_seller_leads', '0004_auto_20200415_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlead',
            name='via_webform',
            field=models.CharField(default='no', max_length=6),
        ),
    ]
