# Generated by Django 2.2.7 on 2020-04-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_seller_leads', '0005_sellerlead_via_webform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerlead',
            name='seller_name',
            field=models.CharField(default='seller_name', max_length=150),
            preserve_default=False,
        ),
    ]
