# Generated by Django 2.2.7 on 2020-04-28 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_seller_leads', '0006_auto_20200421_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerlead',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='temperature',
            field=models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Cold', 'Cold'), ('Hot', 'Hot'), ('Warm', 'Warm'), ('Dead', 'Dead')], max_length=50, null=True),
        ),
    ]
