# Generated by Django 2.2.7 on 2020-04-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_seller_leads', '0007_auto_20200428_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerlead',
            name='deal_details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='detailed_source',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='info',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='mao_details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='miscellaneous_notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='note_for_agent',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='other_terms',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
