# Generated by Django 2.2.7 on 2020-05-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_seller_leads', '0008_auto_20200429_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlead',
            name='call_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='offer_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('New Untouched', 'New Untouched'), ('Discovery', 'Discovery'), ('**Interested--> Updated Offer Status', '**Interested--> Updated Offer Status'), ('Not Interested / Follow Up', 'Not Interested / Follow Up'), ('DO NOT CONTACT', 'DO NOT CONTACT'), ('Solicitation Call / Wrong # / Other', 'Solicitation Call / Wrong # / Other'), ('Wants Retails', 'Wants Retails')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='temperature',
            field=models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Cold', 'Cold'), ('Hot', 'Hot'), ('Warm', 'Warm')], max_length=50, null=True),
        ),
    ]
