# Generated by Django 2.2.7 on 2020-05-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_seller_leads', '0009_auto_20200506_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlead',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
