# Generated by Django 2.2.7 on 2020-05-07 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xforce_seller_leads', '0011_remove_sellerlead_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundRobinCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_task_cc', models.IntegerField(default=0)),
                ('transaction_task_cc', models.IntegerField(default=0)),
                ('sale_task_cc', models.IntegerField(default=0)),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
