# Generated by Django 2.2.7 on 2020-05-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_seller_leads', '0012_roundrobincounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerlead',
            name='best_call_back_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='made_offer',
            field=models.CharField(blank=True, choices=[('No Value', 'No Value'), ('Make Offer', 'Make Offer'), ('Make Attempt 1', 'Make Attempt 1'), ('Make Attempt 2', 'Make Attempt 2'), ('Make Attempt 3', 'Make Attempt 3'), ('Make Attempt 4', 'Make Attempt 4'), ('Made Offer', 'Made Offer'), ('Offer Not Made', 'Offer Not Made')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='stage_of_contact',
            field=models.CharField(blank=True, choices=[('No Attempt', 'No Attempt'), ('Call Attempt 1', 'Call Attempt 1'), ('Call Attempt 2', 'Call Attempt 2'), ('Call Attempt 3', 'Call Attempt 3'), ('Call Attempt 4', 'Call Attempt 4'), ('Final Attempt', 'Final Attempt'), ('CONTACTED', 'CONTACTED')], max_length=50, null=True),
        ),
    ]
