# Generated by Django 2.2.7 on 2020-04-07 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('realtor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('VIP', models.BooleanField(blank=True, default=True, null=True)),
                ('needs_updating', models.BooleanField(blank=True, default=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('target_area', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=255)),
                ('asset_class', models.CharField(blank=True, choices=[('Single Family Residential', 'Single Family Residential'), ('Multi Family', 'Multi Family'), ('Vacant Lots', 'Vacant Lots'), ('Manufactured Home', 'Manufactured Home'), ('Townhomes/ Condos', 'Townhomes/ Condos')], max_length=255, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('type_of_investor', models.CharField(max_length=100)),
                ('price_point', models.CharField(blank=True, choices=[('No Limit', 'No Limit'), ('< $50,000', '< $50,000'), (' $50,001 - $100,000', '$50,001 - $100,000 '), (' $100,001 - $150,000', '$100,001 - $150,000 '), (' $150,001 - $200,000', '$150,001 - $200,000 '), (' $200,001 - $250,000', '$200,001 - $250,000 '), (' $250,001 - $300,000', '$250,001 - $300,000 '), (' $300,001 - $350,000', '$300,001 - $350,000 '), (' $350,001 - $400,000', '$350,001 - $400,000 '), (' $400,001 - $500,000', '$400,001 - $500,000 '), (' $500,001 - $750,000', '$500,001 - $750,000 '), (' $750,001 - $ 1Million', '$750,001 - $ 1Million'), ('> 1Million', '> 1Million')], max_length=255, null=True)),
                ('minimum_return_requirement', models.CharField(blank=True, max_length=255, null=True)),
                ('annual_volume', models.CharField(blank=True, choices=[('1-5(Mom & Pop Investor)', '1-5(Mom & Pop Investor)'), ('6-10', '6-10'), ('11-15', '11-15'), ('16-20', '16-20'), ('20-30', '20-30'), ('31-50', '31-50'), ('51-75', '51-75'), ('76-100', '76-100'), ('100+ (Professional)', '100+ (Professional)')], max_length=255, null=True)),
                ('financing_type', models.CharField(blank=True, choices=[('Cash Purchase', 'Cash Purchase'), ('Hard Money', 'Hard Money'), ('Private Capital', 'Private Capital'), ('IRA', 'IRA'), ('Other', 'Other')], max_length=255, null=True)),
                ('additional_notes', models.TextField(blank=True, max_length=500, null=True)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('Search_query_toi', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='cash_buyer_files/')),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
