"""
Django settings for prospectx_new project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import os

# account_sid_twilio = 'AC9d34b2fa65635e9b8769344f7b0b47f7'
# auth_token_twilio = 'fab42a56d8e547ee469aaedc227cefbb'
# twilio_api_key = 'SK1e09e080c7fc04f88f70f58ff82cb3ec'
# twilio_service = 'ISfa42d332365344adab8e704d4804342a'
account_sid_twilio = ''
auth_token_twilio = ''
twilio_api_key = ''
twilio_service = ''

BASE_API_URL = 'http://127.0.0.1:8888/'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#=9^wtcx76&w1o8%am_!_z)ds%v(l_l)ba%c9y%^qps$uu9sgq'


STRIPE_SECRET_KEY = 'sk_test_BfB8bqkAmYe7aK3vQj7zMR94'
STRIPE_PUBLISHABLE_KEY = 'pk_test_dVBmazomqv3pto0tTQ9mz27a'

# Godaddy developer key and secret
Godaddy_api_key = "3mM44UaggMi4sk_2dUmeCWYXg37nG3zLJWHDS"
Godaddy_secret_key = "MpPjzmP66mbEs52iaUrz1A"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

EMAIL_BACKEND = 'django_smtp_ssl.SSLEmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'shahmeerhussainkhadmi@gmail.com'
EMAIL_HOST_PASSWORD = 'eijq vjrz cmte atnz'
EMAIL_PORT = 465
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'user_management',
    "stripe",
    'user',
    'filter_prospects',
    'payments',
    'marketing_machine',
    'task_management',
    'reports',
    'skiptrace',
    'channels',
    'notification',
    # 'django_eventstream',
    'django_eventstream',
    'daphne',
    'django_elasticsearch_dsl_drf',
    'xsiteApp',
    'xforce',
    'xforce_sales',
    'cash_buyer',
    'xforce_settings',
    'xforce_transactions',
    'xforce_appointment',
    'xforce_seller_leads',
    'affiliate'
]

ASGI_APPLICATION = 'prospectx_new.routing.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

# CELERY STUFF
BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Karachi'

MIDDLEWARE = [
    # 'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prospectx_new.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'task_management.context_processors.context',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'prospectx_new.wsgi.application'

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
#     ),
# }

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'prospectx_xforce',
#         'USER': 'postgres',
#         'PASSWORD': 'a',
#         'HOST': 'localhost',
#         'PORT': '',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

LOGIN_URL = '/'

SESSION_COOKIE_AGE = 60 * 60 * 24 * 30
SESSION_SAVE_EVERY_REQUEST = True
# SESSION_EXPIRE_AT_BROWSER = True
# CORS_ORIGIN_ALLOW_ALL = True

