# Generated by Django 2.2.7 on 2020-04-07 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xforce_seller_leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_date_start', models.DateTimeField(null=True)),
                ('appt_date_end', models.DateTimeField(null=True)),
                ('property_address', models.TextField(max_length=250, null=True)),
                ('offer_acceptance', models.CharField(choices=[('No Value', 'No Value'), ('**Not Accepted - Set Appointment', '**Not Accepted - Set Appointment'), ('**ACCEPTED - Set Appointment', '**ACCEPTED - Set Appointment')], max_length=200, null=True)),
                ('appt_status', models.CharField(choices=[('No Value', 'No Value'), ('COMPLETED', 'COMPLETED'), ('Not Kept', 'Not Kept')], max_length=200, null=True)),
                ('notes', models.TextField(max_length=500, null=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('appt_file', models.FileField(blank=True, null=True, upload_to='appointments_files/')),
                ('going_on_appt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='going_user', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_for_appointment', to='xforce_seller_leads.SellerLead')),
                ('who_set_this_appt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_appt_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
