# Generated by Django 2.2.7 on 2020-04-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appt_date_end',
        ),
    ]
