# Generated by Django 2.2.7 on 2020-04-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xforce_appointment', '0003_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
