# Generated by Django 2.2.7 on 2020-04-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedesign',
            name='html_body_content',
            field=models.CharField(default='nothing', max_length=100000),
        ),
        migrations.AlterField(
            model_name='sitedesign',
            name='html_head_content',
            field=models.CharField(default='nothing', max_length=100000),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='html_body_content',
            field=models.CharField(default='nothing', max_length=100000),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='html_head_content',
            field=models.CharField(default='nothing', max_length=100000),
        ),
    ]
