# Generated by Django 2.2.7 on 2020-04-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsiteApp', '0001_auto_20200411_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedesign',
            name='html_body_content',
            field=models.TextField(default='nothing'),
        ),
        migrations.AlterField(
            model_name='sitedesign',
            name='html_head_content',
            field=models.TextField(default='nothing'),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='html_body_content',
            field=models.TextField(default='nothing'),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='html_head_content',
            field=models.TextField(default='nothing'),
        ),
    ]
