# Generated by Django 2.2.7 on 2020-05-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsiteApp', '0002_auto_20200413_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecontent',
            name='facebook_book_pixel',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='templatecontent',
            name='google_tag_manager',
            field=models.TextField(default=''),
        ),
    ]
