# Generated by Django 2.2.7 on 2020-05-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsiteApp', '0003_auto_20200506_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatecontent',
            name='google_tag_manager',
        ),
        migrations.AddField(
            model_name='templatecontent',
            name='google_tag_manager_body',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='templatecontent',
            name='google_tag_manager_head',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='facebook_book_pixel',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
