# Generated by Django 2.2.7 on 2020-05-19 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xsiteApp', '0004_auto_20200507_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('category_desc', models.CharField(max_length=250)),
                ('category_icon', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Site Category',
            },
        ),
        migrations.AddField(
            model_name='sitedesign',
            name='is_lander_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contentpack',
            name='logo',
            field=models.ImageField(default='xsite_images/website_logos/xsite_logo.png', upload_to='xsite_images/website_logos/'),
        ),
        migrations.AlterField(
            model_name='templatecontent',
            name='logo',
            field=models.ImageField(blank=True, default='xsite_images/website_logos/xsite_logo.png', null=True, upload_to='xsite_images/website_logos/'),
        ),
        migrations.CreateModel(
            name='WebsitePages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50)),
                ('html_head_content', models.TextField(default='nothing')),
                ('html_body_content', models.TextField(default='nothing')),
                ('template_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xsiteApp.TemplateContent')),
            ],
            options={
                'verbose_name_plural': 'Website Page',
            },
        ),
        migrations.AddField(
            model_name='sitedesign',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xsiteApp.SiteCategory'),
        ),
    ]
