# Generated by Django 2.2.7 on 2020-05-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsiteApp', '0005_auto_20200519_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='is_existing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='websites',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
