# Generated by Django 2.2.7 on 2020-04-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', 'User_Data_Migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='xforce_uuid',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
