# Generated by Django 2.2.7 on 2020-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_userprofile_xforce_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('None', 'None'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='None', max_length=20),
        ),
    ]
