# Generated by Django 2.2.7 on 2020-05-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='disposition_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='lead_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='transaction_manager',
            field=models.BooleanField(default=False),
        ),
    ]
