# Generated by Django 2.2.7 on 2020-05-21 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200505_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstripedetail',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
