# Generated by Django 2.2.7 on 2020-05-20 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('billing_amount', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Subscription Plan',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('subscription_status', models.CharField(choices=[('Not Subscribed', 'Not Subscribed'), ('Subscribed', 'Subscribed'), ('Cancelled', 'Cancelled')], default='Not Subscribed', max_length=20)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('next_subscription_plan', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('None', 'None')], default='None', max_length=50)),
                ('account_status', models.CharField(default='active', max_length=10)),
                ('membership_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xforce.SubscriptionPlan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subscription Details',
            },
        ),
    ]
