# Generated by Django 2.2.7 on 2020-05-21 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xforce', '0002_auto_20200520_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='XForceSubscriptionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xforce_subscription_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('xforce_subscription_status', models.CharField(choices=[('Not Subscribed', 'Not Subscribed'), ('Subscribed', 'Subscribed'), ('Cancelled', 'Cancelled')], default='Not Subscribed', max_length=20)),
                ('xforce_subscription_end_date', models.DateField(blank=True, null=True)),
                ('xforce_next_subscription_plan', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('None', 'None')], default='None', max_length=50)),
                ('xforce_account_status', models.CharField(default='active', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subscription Details',
            },
        ),
        migrations.CreateModel(
            name='XForceSubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xforce_plan', models.CharField(max_length=100)),
                ('xforce_billing_amount', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'XForce Subscription Plan',
            },
        ),
        migrations.DeleteModel(
            name='SubscriptionDetails',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.AddField(
            model_name='xforcesubscriptiondetails',
            name='xforce_membership_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xforce.XForceSubscriptionPlan'),
        ),
    ]
